name: Sync submodules

on:
  # push:
  #   branches: [main]
  repository_dispatch:
    types: [update-from-subrepo]

jobs:
  sync-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo (with submodules)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MLOPS_PROD_TOKEN }}
          submodules: recursive

      - name: Set up Git config
        env:
          GH_USER: ${{ secrets.USER }}
          GH_EMAIL: ${{ secrets.EMAIL }}
        run: |
          git config user.name $GH_USER
          git config user.email $GH_EMAIL

      - name: Add submodules if not present
        run: make add-subrepo-remote

      - name: Pull latest changes from submodules
        run: make pull-submodules

      - name: Commit and push if there are changes
        run: make push-submodules
